baseURL = 'http://bakerag1.github.io/preskinole/'
languageCode = 'en-us'
title = 'Preskinole - the Prescott Arizona Crokinole Club'
theme = 'hugo-tranquilpeak-theme'
[Params]
	coverimage = '/cover.jpeg'
